apiVersion: apps/v1
kind: Deployment
metadata: 
  name: churches-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: churches
  template:
    metadata:
      labels:
        app: churches
    spec:
      containers:
        - name: churches
          image: rhassard/churches:latest
          env: 
            - name: MONGO_URI
              value: 'mongodb://churches-mongo-srv:27017/churches'
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: churches-srv
spec:
  selector:
    app: churches
  ports:
    - name: churches
      protocol: TCP
      port: 3000
      targetPort: 3000