apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
spec:
  rules:
    - host: pros.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend: 
              serviceName: auth-srv
              servicePort: 3000
          - path: /api/churches/?(.*)
            backend: 
              serviceName: churches-srv
              servicePort: 3000
          - path: /api/corporates/?(.*)
            backend: 
              serviceName: corporates-srv
              servicePort: 3000
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
    - host: pros.app
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: app-srv
              servicePort: 8100